spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
        show-details: always

info:
  app:
    author: fufeng
    encoding: @project.build.sourceEncoding@
