server:
  port: 8090

feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
