server:
  port: 0

management:
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
