spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

redis:
  host: 192.168.0.170
  maxTotal: 5
  maxIdle: 5
  testOnBorrow: true

#redis.max-total=3
#redis.max-idle=3
#redis.test-on-borrow=true