server:
  port: 9990

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9999/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: zuul-server
