server:
  port: 9990

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9999/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: zuul-server

zuul:
  routes:
    user-service: /user/**
    baidu:
      path: /baidu/**
      url: http://www.baidu.com/baidu
    thirdpartyservice:
      path: /thirdpartyservice/**
      serviceId: thirdpartyservice
  prefix: /health
  ignored-services: 'user-service'

ribbon:
  eureka:
    enabled: false

thirdpartyservice:
  ribbon:
    listOfServers: http://thirdpartyservice1:8080,http://thirdpartyservice2:8080

