spring:
  application:
    name: provider-service # 应用/微服务名称
  cloud:
   nacos:
     discovery:
       server-addr: 127.0.0.1:8848 # nacos 服务地址
       username: nacos
       password: nacos
server:
  port: 7890
