server:
  port: 0

customer:
  name: spring-${server.port}

feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    stream:
      rabbit:
        bindings:
          notifyOrders:
            consumer:
              binding-routing-key: ${customer.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: spring


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    author: fufeng
    encoding: @project.build.sourceEncoding@

resilience4j:
  ratelimiter:
    limiters:
      coffee:
        limit-for-period: 5
        limit-refresh-period-in-millis: 30000
        timeout-in-millis: 5000
        subscribe-for-events: true
        register-health-indicator: true
      order:
        limit-for-period: 3
        limit-refresh-period-in-millis: 30000
        timeout-in-millis: 1000
        subscribe-for-events: true
        register-health-indicator: true
  bulkhead:
    backends:
      order:
        max-concurrent-call: 1
        max-wait-time: 5
      menu:
        max-concurrent-call: 5
        max-wait-time: 5
