spring:
  profiles:
    active: consul-provider1

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: consul-provider1
  application:
    name: consul-provider1

server:
  port: 5001

---
spring:
  profiles: consul-provider2
  application:
    name: consul-provider2

server:
  port: 5002