spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

  redis:
    host: 192.168.0.170
    lettuce:
      pool:
        maxActive: 5
        maxIdle: 5