spring:
  application:
    name: warehouse-service # 引用微服务名称，仓储服务
  cloud:
    nacos:
      discovery:
        #server-addr: 238019z50f.zicp.vip:80
        server-addr: 192.168.0.170:8848
        username: nacos
        password: nacos
server:
  port: 7890
dubbo: #dubbo与nacos的通信配置
  application:
    name: warehouse-house  #provider在Nacos中的应用id
  registry: #Provider与Nacos通信地址，与spring.cloud.nacos地址一致
    address: nacos://192.168.0.170:8848
  protocol:
    name: dubbo #通信协议名
    port: 20880 #配置通信端口，默认为20880
  scan:
    base-packages: org.fufeng.sca.warehouse.dubbo