spring:
  profiles:
    active: stream-rabbit-customer-group1

---
spring:
  profiles: stream-rabbit-customer-group1
  cloud:
    stream:
      bindings:
        #        input:
        #          destination: default.messages
        #          binder: local_rabbit
        #        output:
        #          destination: default.messages
        #          binder: local_rabbit
        log_input:
          destination: wkx.log.messages
          binder: local_rabbit
          group: logConsumer-group1
        log_output:
          destination: wkx.log.messages
          binder: local_rabbit
          group: logConsumer-group1
        log_format_input:
          destination: wkx.log.format.messages
          binder: local_rabbit
          group: logFormat-group1
        log_format_output:
          destination: wkx.log.format.messages
          binder: local_rabbit
          group: logFormat-group1
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
server:
  port: 8201

---
spring:
  profiles: stream-rabbit-customer-group2
  cloud:
    stream:
      bindings:
        #        input:
        #          destination: default.messages
        #          binder: local_rabbit
        #        output:
        #          destination: default.messages
        #          binder: local_rabbit
        log_input:
          destination: wkx.log.messages
          binder: local_rabbit
          group: logConsumer-group2
        log_output:
          destination: wkx.log.messages
          binder: local_rabbit
        log_format_input:
          destination: wkx.log.format.messages
          binder: local_rabbit
          group: logFormat-group1
        log_format_output:
          destination: wkx.log.format.messages
          binder: local_rabbit
          group: logFormat-group1
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
server:
  port: 8203