server:
  port: 10000
spring:
  application:
    name: gateway
  #  redis:
  #    database: 0
  #    host: localhost
  #    port: 6379
  #    password: 123456
  #    jedis:
  #      pool:
  #        max-active: 8
  #        max-idle: 8
  #        min-idle: 0
  #    timeout: 100ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
# 配置文件实现路由规则
#      routes:
#        - id: userServiceRouter
#          uri: lb://consul-user
#          predicates:
#            - Path=/user-service/**
##          filters:
##            - StripPrefix=1
#        - id: orderServiceRouter
#          uri: lb://consul-order
#          predicates:
#            - Path=/order-service/**
#          filters:
#            - StripPrefix=1  # 设置跳过URI中的第一段
    consul:
      host: localhost #注册gateway网关到consul
      port: 8500
      discovery:
        service-name: service-gateway
#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            client-id: gateway-client
#            client-secret: gateway-secret
#            authorization-grant-type: password
#            #authorization-grant-type: authorization_code
#            #redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
#            clientName: gateway
#        provider:
#          oauth-server:
#            user-authorization-uri: http://localhost:5010/oauth-service/oauth/authorize
#            access-token-uri: http://localhost:5010/oauth-service/oauth/token
#            jwt-key-uri: dev

#hystrix:
#  command:
#    second2Command:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000