spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    static-path-pattern: /static/**
  resources:
    cache:
      cachecontrol:
        max-age: 20s
#spring.resources.cache.cachecontrol.no-cache=true