@startuml
'https://plantuml.com/class-diagram

interface Servlet
interface ServletConfig
abstract class GenericServlet
abstract class HttpServlet

Servlet <|-- GenericServlet
ServletConfig <|-- GenericServlet
GenericServlet <|-- HttpServlet



@enduml