spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: '*'

  cache:
    type: redis
    cache-names: coffee
    redis:
      time-to-live: 5000
      cache-null-values: false

  redis:
    host: 192.168.0.170