server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  demo:
    name: Spring Boot Admin Client Demo

spring:
  application:
    name: sba-client

  security:
    user:
      name: fufeng
      password: 123456

  boot:
    admin:
      client:
        url: http://localhost:8080
        username: fufeng
        password: 123456

        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}