spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  # 配置方式实现压缩声明
  # curl -H "Accept-Encoding: gzip" -v http://localhost:8080/coffee/1
  compression:
    enabled: true
    min-response-size: 512B
  error:
    include-stacktrace: always
    include-exception: true