CREATE TABLE STOCK(
    SYMBOL VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255)
    );

CREATE TABLE STOCK_SUBSCRIPTION(
    ID BIGINT PRIMARY KEY,
    EMAIL VARCHAR(255),
    SYMBOL VARCHAR(255)
    );